package spring.boot.demo.dao.generate.demo;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class AcctKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct.acctnbr
     *
     * @mbg.generated Thu Sep 05 10:27:40 CST 2019
     */
    private String acctnbr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct.acctnbr
     *
     * @return the value of acct.acctnbr
     *
     * @mbg.generated Thu Sep 05 10:27:40 CST 2019
     */
    public String getAcctnbr() {
        return acctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct.acctnbr
     *
     * @param acctnbr the value for acct.acctnbr
     *
     * @mbg.generated Thu Sep 05 10:27:40 CST 2019
     */
    public void setAcctnbr(String acctnbr) {
        this.acctnbr = acctnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct
     *
     * @mbg.generated Thu Sep 05 10:27:40 CST 2019
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
}