package spring.boot.demo.dao.generate.demo;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class Acct extends AcctKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct.name
     *
     * @mbg.generated Thu Sep 05 10:27:40 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct.name
     *
     * @return the value of acct.name
     *
     * @mbg.generated Thu Sep 05 10:27:40 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct.name
     *
     * @param name the value for acct.name
     *
     * @mbg.generated Thu Sep 05 10:27:40 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct
     *
     * @mbg.generated Thu Sep 05 10:27:40 CST 2019
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
}